import { CompanyViewModel } from './CompanyViewModel';
import {UUID} from 'angular2-uuid';

export class PersonViewModel {
    public Id: UUID;
    public FullName: string;
    public DateOfBirth: Date;
    public PlaceOfBirth: string;
    public Position: string;
    public SourceOfAuthority: string;
    public FullPowersDocumentsNames: string;
    public Login: string;
    public Password: string;
    public EDS_type: number;
    public PossibilityToInputContract: boolean;
    public PossibilityToExposeBid: boolean;
    public PossibilityToExposeBidWithoutRestrictions: boolean;
    public LimitOfSumOfEveryBid: number;
    public LimitOfCommonSumOfNotCalculatedBids: number;
    public CounterOfferAcceptPossibility: boolean;
    public CounterOfferAcceptPossibilityWithoutRestrictions: boolean;
    public LimitOfDeviationRateFromInitialBidInPercentage: number;
    public LimitOfDeviationByDiscountFromStartBid: number;
    public PossibilityToAddAndEditNewUsers: boolean;
    public PossibilityToChangeCompanyInformation: boolean;
    public IdentityDocumentsNames: string;
    public PossibilityType: number;
    public UserRestrictions: boolean;
    public LimitOfOneBid: number;
    public TotalLimitForAllUnsettledBidsAndCounterOffer: number;
    public LimitUsettledDebtOnOneSupplierTakingIntoAccountTheCreditQuality: number;
    public PossibilityToAddNewUsers: boolean;
    public PossibilityToEditNewUsers: boolean;
    public Citizenship: string;
    public Occupation: string;
    public MobilePhone: string;
    public AuthDocumentType: string;
    public AuthDocumentURL: string;
    public AuthDateFrom: Date;
    public AuthDateTo: Date;
    public NewPassword: string;
    public GetDocsBaseUrl: string;
    public DeleteDocsBaseUrl: string;
    public IsActive: boolean;
    public Company: CompanyViewModel;
}